### ISSUE TITLE
Get error path should be string not StringIO

### ISSUE THREAD

**Issue by naxim92** [decryptus/json-dotenv#4]
I use on Windows and get the error when run it

Command & error:
```
json-dotenv list -f private/.env

ERROR:2023-04-21 20:45:04: stat: path should be string, bytes, os.PathLike or integer, not StringIO
Traceback (most recent call last):
  File "venv\Scripts\json-dotenv.py", line 462, in main
    getattr(JsonDotEnv(options), "do_%s" % options.command)()
  File "venv\Scripts\json-dotenv.py", line 337, in do_list
    dotenv.dotenv_values(self.fcontent)))
  File "venv\lib\site-packages\dotenv\main.py", line 375, in dotenv_values
    return DotEnv(
  File "venv\lib\site-packages\dotenv\main.py", line 75, in dict
    self._dict = OrderedDict(resolve_variables(raw_values, override=self.override))
  File "venv\lib\site-packages\dotenv\main.py", line 233, in resolve_variables
    for (name, value) in values:
  File "venv\lib\site-packages\dotenv\main.py", line 82, in parse
    with self._get_stream() as stream:
  File "C:\Program Files\Python39\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "venv\lib\site-packages\dotenv\main.py", line 54, in _get_stream
    if self.dotenv_path and os.path.isfile(self.dotenv_path):
  File "C:\Program Files\Python39\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not StringIO
```
I could fix the problem by adding **stream** argument to dotenv.dotenv_values execution like I read in a [doc](https://pypi.org/project/python-dotenv/):
```
load_dotenv and dotenv_values accept [streams](https://docs.python.org/3/library/io.html) via their stream argument. It is thus possible to load the variables from sources other than the filesystem (e.g. the network).

from io import StringIO

from dotenv import load_dotenv

config = StringIO("USER=foo\nEMAIL=foo@example.org")
load_dotenv(stream=config)
```

Windows 10
Python 3.9.2
json-dotenv     0.0.28
python-dotenv   1.0.0

**Comment by decryptus** [comment]
Hi @naxim92,

Thanks for the bug report!

Fixed in release: 0.0.29

Best regards
